#!/usr/bin/env python3
"""
build_blocklist.py — compile domain lists into a dnsmasq blocklist.

This is the enforcement half of your DNS filter. It reads plain lists of
domains (one per line) that you want BLOCKED, subtracts any you want ALLOWED,
and writes /etc/netlab/blocklist.hosts in the hosts format dnsmasq loads
(`0.0.0.0 domain`). A blocked domain then resolves to 0.0.0.0 for every device
on your LAN, so the site simply doesn't load.

Where your "AI DNS server" plugs in: right now categories come from static
list files (drop e.g. an adult-sites list in dns_resolver/lists/). Later,
replace/extend the `classify()` hook below with your model — return True to
block a domain, False to allow it — and this script becomes your model's
deploy step.

Lists are yours and can be large/sensitive, so keep them in dns_resolver/lists/
(git-ignored) rather than committing them.

Usage:
    # block everything in these files, keep allowlist exceptions:
    sudo python3 dns_resolver/build_blocklist.py \
        --block dns_resolver/lists/adult.txt --block dns_resolver/lists/ads.txt \
        --allow dns_resolver/lists/allow.txt --reload

    # dry run (print what would be blocked, write nothing):
    python3 dns_resolver/build_blocklist.py --block dns_resolver/lists/adult.txt --dry-run

    python3 dns_resolver/build_blocklist.py --help
"""
import argparse
import os
import re
import subprocess
import sys

OUT = "/etc/netlab/blocklist.hosts"
DOMAIN_RE = re.compile(r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$")


def read_domains(path):
    """Read a list file. Accepts plain domains or `0.0.0.0 domain` hosts lines."""
    out = set()
    try:
        with open(path, "r", errors="replace") as fh:
            for raw in fh:
                line = raw.strip().lower()
                if not line or line.startswith(("#", "!")):
                    continue
                parts = line.split()
                dom = parts[-1] if len(parts) > 1 else parts[0]  # tolerate hosts format
                dom = dom.rstrip(".")
                if DOMAIN_RE.match(dom):
                    out.add(dom)
    except FileNotFoundError:
        sys.exit(f"List not found: {path}")
    return out


def classify(domain: str) -> bool:
    """AI HOOK — decide whether to block a domain.

    Default policy: block nothing here (the list files do the work). Replace the
    body with a call to your model/classifier and return True to BLOCK, False to
    ALLOW. Runs for every candidate domain, so keep it fast or cache results.
    """
    return False  # <-- your AI DNS logic goes here


def main() -> int:
    ap = argparse.ArgumentParser(description="Compile domain lists into a dnsmasq blocklist.")
    ap.add_argument("--block", action="append", default=[], metavar="FILE",
                    help="file of domains to block (repeatable)")
    ap.add_argument("--allow", action="append", default=[], metavar="FILE",
                    help="file of domains to always allow (repeatable)")
    ap.add_argument("--out", default=OUT, help=f"output hosts file (default {OUT})")
    ap.add_argument("--dry-run", action="store_true", help="print result, write nothing")
    ap.add_argument("--reload", action="store_true", help="SIGHUP dnsmasq to apply")
    args = ap.parse_args()

    blocked = set()
    for f in args.block:
        blocked |= read_domains(f)
    allowed = set()
    for f in args.allow:
        allowed |= read_domains(f)

    # Apply the AI hook, then subtract the allowlist (allow always wins).
    blocked |= {d for d in blocked if classify(d)}
    final = sorted(blocked - allowed)

    print(f"[*] {len(blocked)} blocked, {len(allowed)} allowed -> {len(final)} effective domains")
    if args.dry_run:
        for d in final[:50]:
            print("  ", d)
        if len(final) > 50:
            print(f"   ... and {len(final) - 50} more")
        print("[*] Dry run — nothing written.")
        return 0

    header = "# Generated by dns_resolver/build_blocklist.py — do not hand-edit.\n"
    body = "".join(f"0.0.0.0 {d}\n" for d in final)
    try:
        with open(args.out, "w") as fh:
            fh.write(header + body)
    except PermissionError:
        sys.exit(f"Cannot write {args.out} — re-run with sudo.")
    print(f"[*] Wrote {args.out}")

    # The resolver's service name is recorded by setup_resolver.sh.
    svc = "netlab-dnsmasq"
    try:
        with open("/etc/netlab/service") as fh:
            svc = fh.read().strip() or svc
    except OSError:
        pass

    if args.reload:
        try:
            subprocess.run(["systemctl", "reload", svc], check=True)
            print(f"[*] Reloaded {svc} — blocklist is live.")
        except (subprocess.CalledProcessError, FileNotFoundError):
            print(f"[!] Could not reload; run: sudo systemctl reload {svc}", file=sys.stderr)
    else:
        print(f"[*] Apply with: sudo systemctl reload {svc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
